import adminDB from '@/lib/adminDB';
import platformAPI from '@/lib/platformAPI';
import { getSystemPrompt } from '@/utils/systemPrompt';
import { openai } from '@ai-sdk/openai';
import { id, User } from '@instantdb/react-native';
import { streamText } from 'ai';
import { runTask } from 'expo-server';

export async function POST(req: Request) {
  const { prompt } = await req.json();

  const token = req.headers.get('RefreshToken');

  if (!token) {
    return Response.json({ message: 'You must be authenticated' }, { status: 400 });
  }

  const user = await adminDB.auth.verifyToken(token);

  if (!user) {
    return Response.json({ message: 'You are not authenticated' }, { status: 401 });
  }

  console.log('User verified');

  try {
    const friendlyTitle = prompt.slice(0, 100);
    const buildId = id();

    await createBuild(user, { buildId, friendlyTitle });

    // THIS ACTUALLY GENERATES THE CODE
    runTask(async () => {
      await callOpenAI({ prompt, user, buildId });
    });

    return Response.json({ buildId });
  } catch (error: any) {
    return Response.json({ success: false, error: 'Internal server error' }, { status: 500 });
  }
}

async function callOpenAI({
  prompt,
  user,
  buildId,
}: {
  prompt: string;
  user: User;
  buildId: string;
}) {
  let reasoning = '';
  let code = '';
  let isPreviewable = false;

  let isPending = false;
  let needsAnotherSave = false;

  let triggerSave = async () => {
    if (isPending) {
      needsAnotherSave = true;
      return;
    }
    isPending = true;

    while (true) {
      needsAnotherSave = false;
      try {
        await adminDB
          .asUser({ email: user.email! })
          .transact([adminDB.tx.builds[buildId].update({ code: code, isPreviewable, reasoning })]);
      } catch (error) {
        console.error('Error saving build:', error);
      }

      if (!needsAnotherSave) {
        break;
      }
    }

    isPending = false;
  };

  const { fullStream } = streamText({
    model: openai('gpt-5-codex'),
    prompt: prompt,
    system: getSystemPrompt(),
    providerOptions: {
      openai: {
        reasoningSummary: 'detailed',
        reasoningEffort: 'low',
      },
    },
    onError: (error) => {
      console.error('Error streaming text:', error);
    },
  });

  for await (const chunk of fullStream) {
    switch (chunk.type) {
      case 'text-delta':
        code += chunk.text;
        triggerSave();
        break;
      case 'reasoning-delta':
        reasoning += chunk.text;
        triggerSave();
        break;
      default:
        console.log('step: ', chunk.type);
        break;
    }
  }

  isPreviewable = true;
  triggerSave();
}

async function createBuild(
  user: User,
  {
    buildId,
    friendlyTitle,
  }: {
    buildId: string;
    friendlyTitle: string;
  }
) {
  // Create a new Instant App
  const { app: instantApp } = await platformAPI.createApp({
    title: friendlyTitle,
    orgId: process.env.INSTANT_ORG_ID!,
  });
  console.log('Create build with Instant App ID: ', instantApp);
  console.log('Build ID: ', buildId);
  console.log('User email: ', user.email);
  console.log('user id: ', user.id);

  const build = {
    id: buildId,
    instantAppId: instantApp.id, // instantApp.id,
    code: '', // will be generated by the LLM
    isPreviewable: false,
    title: friendlyTitle,
  };

  // Add the build with the generated Instant App ID and link it to the user
  try {
    const result = await adminDB
      .asUser({ email: user.email! })
      .transact([adminDB.tx.builds[buildId].create(build).link({ owner: user.id })]);
    console.log('Build created', result);
  } catch (error: any) {
    console.error('Error creating build', error);
  }

  return build;
}
